#!/bin/sh

#---------------------#
# Meoboot init by meo #
#---------------------#

if [ $1 == "ubiroot" ]; then

	/etc/init.d/sysfs.sh
	/etc/init.d/modutils.sh
#	/etc/init.d/udev start  > /dev/null 2>&1
	mknod /dev/sda b  8 0
	mknod /dev/sda1 b 8 1
	mknod /dev/sda2 b 8 2
	mknod /dev/sdb b  8 16
	mknod /dev/sdb1 b 8 17
	mknod /dev/sdb2 b 8 18
	mknod /dev/sdc b  8 32
	mknod /dev/sdc1 b 8 33
	mknod /dev/sdc2 b 8 34
	mknod /dev/sdd b  8 48
	mknod /dev/sdd1 b 8 49
	mknod /dev/sdd2 b 8 50

	mkdir /dev/input
	mknod /dev/input/event0 c 13 64

	mknod /dev/fb0 c 29 0
	mkdir /dev/fb
	ln -s ../fb0 /dev/fb/0

	sleep 1
	cat /etc/videomode > /proc/stb/video/videomode

	DEVICES1=`find /dev/sd??`
	for DEVICE in $DEVICES1;
	do
		if [ ! -e /media/meoboot/MbootM/.meoboot  ]; then
     		mount $DEVICE /media/meoboot > /dev/null 2>&1
    	fi
   		if [ ! -e /media/meoboot/MbootM/.meoboot  ]; then
       		umount /media/meoboot > /dev/null 2>&1 
    	fi 
	done
	
	/usr/bin/showiframe /usr/lib/enigma2/python/Plugins/Extensions/MeoBoot/icons/meoboot_i.mvi > /dev/null 2>&1
	/usr/lib/enigma2/python/Plugins/Extensions/MeoBoot/contrib/meobm
	/usr/bin/showiframe /usr/share/bootlogo.mvi
	
	TARGET="Flash"
	if [ -f /media/meoboot/MbootM/.meoboot ]; then
		TARGET=`cat /media/meoboot/MbootM/.meoboot`
	fi
	
	if [ $TARGET != "Flash" ]; then
		/bin/mount -o bind /dev /media/meoboot/MbootM/$TARGET/dev
		/bin/mount -o bind /proc /media/meoboot/MbootM/$TARGET/proc
		/bin/mount -o bind /sys /media/meoboot/MbootM/$TARGET/sys
		rm  /media/meoboot/MbootM/$TARGET/media/meoboot > /dev/null 2>&1
		mkdir /media/meoboot/MbootM/$TARGET/media/meoboot > /dev/null 2>&1
		if [ ! -f /media/meoboot/MbootM/$TARGET/media/meoboot/MbootM/.meoboot ]; then
            /bin/mount -o bind /media/meoboot /media/meoboot/MbootM/$TARGET/media/meoboot
		fi
		
		DEVICES1=`ls /media`
		for DEVICE in $DEVICES1;
		do
			if [ -f /media/$DEVICE/MbootM/.meoboot ]; then
				/bin/mount -o bind /media/meoboot /media/meoboot/MbootM/$TARGET/media/$DEVICE
			fi
		done
		
		cd /media/meoboot/MbootM/$TARGET;
		exec /usr/sbin/chroot . /sbin/init.sysvinit $*
	else
		exec /sbin/init.sysvinit $*
	fi

else
	exec /sbin/init.sysvinit $*
fi

exit 0
